<?php

/**
 * BasePullRequestComment
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $pull_request_id
 * @property integer $author_id
 * @property clob $body
 * @property PullRequest $PullRequest
 * @property sfGuardUser $Author
 * 
 * @method integer            getPullRequestId()   Returns the current record's "pull_request_id" value
 * @method integer            getAuthorId()        Returns the current record's "author_id" value
 * @method clob               getBody()            Returns the current record's "body" value
 * @method PullRequest        getPullRequest()     Returns the current record's "PullRequest" value
 * @method sfGuardUser        getAuthor()          Returns the current record's "Author" value
 * @method PullRequestComment setPullRequestId()   Sets the current record's "pull_request_id" value
 * @method PullRequestComment setAuthorId()        Sets the current record's "author_id" value
 * @method PullRequestComment setBody()            Sets the current record's "body" value
 * @method PullRequestComment setPullRequest()     Sets the current record's "PullRequest" value
 * @method PullRequestComment setAuthor()          Sets the current record's "Author" value
 * 
 * @package    skeleton
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasePullRequestComment extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('pull_request_comment');
        $this->hasColumn('pull_request_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('author_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('body', 'clob', null, array(
             'type' => 'clob',
             'notnull' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('PullRequest', array(
             'local' => 'pull_request_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('sfGuardUser as Author', array(
             'local' => 'author_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $timestampable0 = new Doctrine_Template_Timestampable(array(
             ));
        $this->actAs($timestampable0);
    }
}