<?php

/**
 * BaseTag
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $name
 * @property string $text_color
 * @property string $background_color
 * @property Doctrine_Collection $Issues
 * @property Doctrine_Collection $IssueTags
 * 
 * @method string              getName()             Returns the current record's "name" value
 * @method string              getTextColor()        Returns the current record's "text_color" value
 * @method string              getBackgroundColor()  Returns the current record's "background_color" value
 * @method Doctrine_Collection getIssues()           Returns the current record's "Issues" collection
 * @method Doctrine_Collection getIssueTags()        Returns the current record's "IssueTags" collection
 * @method Tag                 setName()             Sets the current record's "name" value
 * @method Tag                 setTextColor()        Sets the current record's "text_color" value
 * @method Tag                 setBackgroundColor()  Sets the current record's "background_color" value
 * @method Tag                 setIssues()           Sets the current record's "Issues" collection
 * @method Tag                 setIssueTags()        Sets the current record's "IssueTags" collection
 * 
 * @package    skeleton
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseTag extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('tag');
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('text_color', 'string', 255, array(
             'type' => 'string',
             'default' => '#333',
             'length' => 255,
             ));
        $this->hasColumn('background_color', 'string', 255, array(
             'type' => 'string',
             'default' => '#FFF',
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Issue as Issues', array(
             'refClass' => 'IssueTag',
             'local' => 'tag_id',
             'foreign' => 'issue_id'));

        $this->hasMany('IssueTag as IssueTags', array(
             'local' => 'id',
             'foreign' => 'tag_id'));

        $timestampable0 = new Doctrine_Template_Timestampable(array(
             ));
        $this->actAs($timestampable0);
    }
}