<?php

/**
 * IssueCommentTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class IssueCommentTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object IssueCommentTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('IssueComment');
    }
}