<?php

/**
 * IssueTagTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class IssueTagTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object IssueTagTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('IssueTag');
    }
}