<?php

/**
 * IssueTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class IssueTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object IssueTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Issue');
    }
}