<?php

/**
 * PullRequestTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PullRequestTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PullRequestTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PullRequest');
    }
}