sf_guard_user_sf_guard_user_old:
  class: sfDoctrineRouteCollection
  options:
    model:                sfGuardUser
    module:               sf_guard_user_old
    prefix_path:          /sf_guard_user_old
    column:               id
    with_wildcard_routes: true

pull_request_comment:
  class: sfDoctrineRouteCollection
  options:
    model:                PullRequestComment
    module:               pull_request_comment
    prefix_path:          /pull_request_comment
    column:               id
    with_wildcard_routes: true

tag:
  class: sfHadoriAdminRouteCollection
  options:
    model:                Tag
    module:               tag
    prefix_path:          /tag
    column:               id
    with_wildcard_routes: true
    with_export:          true

issue:
  class: sfHadoriAdminRouteCollection
  options:
    model:                Issue
    module:               issue
    prefix_path:          /issue
    column:               id
    with_wildcard_routes: true
    with_export:          true

pull_request:
  class: sfHadoriAdminRouteCollection
  options:
    model:                PullRequest
    module:               pull_request
    prefix_path:          /pull_request
    column:               id
    with_wildcard_routes: true
    with_export:          true

sf_guard_user:
  class: sfHadoriAdminRouteCollection
  options:
    model:                sfGuardUser
    module:               sf_guard_user
    prefix_path:          /sf_guard_user
    column:               id
    with_wildcard_routes: true
    with_export:          true

# default rules
homepage:
  url:   /
  param: { module: sf_guard_user, action: index }

default_index:
  url:   /:module
  param: { action: index }

default:
  url:   /:module/:action/*
