default:
  http_metas:
    content-type: text/html

  metas:
    title:        Hadori Demo
    #description:  symfony project
    #keywords:     symfony, project
    #language:     en
    #robots:       index, follow

  stylesheets:
    - reset.css
    - text.css
    - /sfHadoriThemePlugin/css/theme.css
    - /sfHadoriThemePlugin/css/hadori.css
    - style.css

  javascripts:
    - /sfHadoriThemePlugin/js/jquery-1.4.2.min.js
    - /sfHadoriThemePlugin/js/hadori.js

  has_layout:     true
  layout:         layout
